src/Entity/Oeuvre.php
<?php

namespace App\Entity;

use App\Repository\OeuvreRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Gedmo\Mapping\Annotation as Gedmo;

#[ORM\Entity(repositoryClass: OeuvreRepository::class)]
class Oeuvre
{
    #[ORM\Id]
    #[ORM\GeneratedValue(strategy: "IDENTITY")]
    #[ORM\Column(name: "id", type: "integer", nullable: false)]
    private $id;

    #[ORM\Column(name: "nom_Oeuvre", type: "string", length: 255, nullable: false)]
    private $nomOeuvre;

    #[ORM\Column(name: "img", type: "string", length: 255, nullable: false)]
    private $img;

    #[ORM\Column(name: "description", type: "string", length: 255, nullable: false)]
    private $description;

    #[ORM\Column(name: "TypeOeuvre", type: "string", length: 2555, nullable: false)]
    private $typeoeuvre;

    #[ORM\Column(name: "date_Publication", type: "date", nullable: false)]
    private $datePublication;

    #[ORM\Column(name: "note", type: "integer", nullable: false)]
    private $note;

    #[ORM\ManyToOne(targetEntity: "User")]
    #[ORM\JoinColumn(name: "artiste_id", referencedColumnName: "id")]
    private $artiste;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNomOeuvre(): ?string
    {
        return $this->nomOeuvre;
    }

    public function setNomOeuvre(string $nomOeuvre): static
    {
        $this->nomOeuvre = $nomOeuvre;

        return $this;
    }

    public function getImg(): ?string
    {
        return $this->img;
    }

    public function setImg(string $img): static
    {
        $this->img = $img;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): static
    {
        $this->description = $description;

        return $this;
    }

    public function getTypeoeuvre(): ?string
    {
        return $this->typeoeuvre;
    }

    public function setTypeoeuvre(string $typeoeuvre): static
    {
        $this->typeoeuvre = $typeoeuvre;

        return $this;
    }

    public function getDatePublication(): ?\DateTimeInterface
    {
        return $this->datePublication;
    }

    public function setDatePublication(\DateTimeInterface $datePublication): static
    {
        $this->datePublication = $datePublication;

        return $this;
    }

    public function getNote(): ?int
    {
        return $this->note;
    }

    public function setNote(int $note): static
    {
        $this->note = $note;

        return $this;
    }

    public function getArtisteId(): ?User
    {
        return $this->artiste;
    }

    public function setArtisteId(?User $artiste): static
    {
        $this->artiste = $artiste;

        return $this;
    }
}

src/Form/OeuvreType.php
<?php

namespace App\Form;

use App\Entity\Oeuvre;
use App\Entity\User;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\IntegerType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\Validator\Constraints\File;
use Symfony\Component\Validator\Constraints\NotBlank;
use Symfony\Component\Validator\Constraints\Length;
use DateTime;

class OeuvreType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            
            ->add('nomOeuvre',null,[
                'constraints' => [
                    new NotBlank([
                        'message' => 'Le nom ne peut pas être vide.',
                    ]),
                    new Length([
                        'min' => 4,
                        'max' => 255,
                        'minMessage' => 'Le nom doit avoir au moins {{ limit }} caractères.',
                        'maxMessage' => 'Le nom ne peut pas dépasser {{ limit }} caractères.',
                    ]),
                ],
            ])
        
            ->add('img', FileType::class, [
                'required' => false,
                'mapped' => false,
                'constraints' => [
                    new File([
                        'maxSize' => '1024k',
                        'mimeTypes' => [
                            'image/jpeg',
                            'image/png',
                        ],
                        'mimeTypesMessage' => 'Veuillez télécharger un fichier image valide (JPEG, PNG).',
                    ]),
                ],
            ])
            ->add('description')
            ->add(
                'typeoeuvre',
                ChoiceType::class,
                [
                    'choices' => [
                        'Film' => 'FILM',  //choiceType pour statique
                        'Chanson' => 'CHANSON',
                        'Piece_théatre' => 'PIECETHEATRE'
                    ],
                    'expanded' => false
                ], //expended list Select  (false) 
                ['multiple' => false] //check box true , radio false
            )
            ->add('datePublication')
            ->add('note')
            
            ->add('Ajouter', SubmitType::class);;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Oeuvre::class,
        ]);
    }
    
}

src/Controller/OeuvreController.php
<?php

namespace App\Controller;

use Symfony\Component\HttpFoundation\File\UploadedFile;
use Symfony\Component\Security\Core\Security;
use App\Entity\Oeuvre;
use App\Entity\Like;
use App\Entity\User;
use Endroid\QrCode\QrCode;
use Endroid\QrCode\Encoding\Encoding;
use Endroid\QrCode\Color\Color;
use Endroid\QrCode\Label\Label;
use Endroid\QrCode\Label\Font\NotoSans;
use Endroid\QrCode\ErrorCorrectionLevel;
use Endroid\QrCode\Writer\PngWriter;
use App\Form\OeuvreType;
use App\Repository\OeuvreRepository;
use Doctrine\Persistence\ManagerRegistry;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Form\Test\FormInterface;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Knp\Component\Pager\PaginatorInterface;
use Symfony\Component\Notifier\Notification\Notification;
use Symfony\Component\Notifier\NotifierInterface;
use App\Entity\OeuvreNotification;
use App\Repository\UserRepository;

class OeuvreController extends AbstractController
{

    #[Route('/listeOeuvre', name: 'app_artiste_oeuvre')]
public function listeOeuvre(OeuvreRepository $repo, PaginatorInterface $paginator, Request $request): Response
{
    // Get the type parameter from the request
    $type = $request->query->get('typeoeuvre');

    // Get all oeuvres query
    $query = $repo->createQueryBuilder('o');

    // Filter by type if the type parameter is provided
    if ($type && $type !== 'all') {
        $query->andWhere('o.typeoeuvre = :type')
              ->setParameter('type', $type);
    }

    $query = $query->getQuery();

    // Paginate the query results
    $oeuvres = $paginator->paginate(
        $query,
        $request->query->getInt('page', 1), // Get the page number from the request, default to 1
        6 // Number of items per page
    );

    return $this->render('app/listoeuvres.html.twig', ['oeuvres' => $oeuvres]);
}
#[Route('/artiste/listeOeuvre', name: 'app_oeuvre')]
public function listeOeuvre1(OeuvreRepository $repo, PaginatorInterface $paginator, Request $request, Security $security): Response
{
    // Get the currently logged-in user
    $user = $security->getUser();

    // Check if a user is logged in
    if (!$user) {
        // Redirect or show an error message
        // For example, return a 403 Forbidden response
        return new Response('You are not authorized to view this page.', Response::HTTP_FORBIDDEN);
    }

    // Get all oeuvres associated with the currently logged-in user
    $oeuvres = $repo->findByArtiste($user);

    // Paginate the query results
    $oeuvres = $paginator->paginate(
        $oeuvres,
        $request->query->getInt('page', 1), // Get the page number from the request, default to 1
        3 // Number of items per page
    );

    return $this->render('oeuvre/oeuvre.html.twig', ['oeuvres' => $oeuvres]);
}


    
    #[Route('/artiste/addOeuvre', name: 'app_add_oeuvre')]
    public function addOeuvre(Request $request, ManagerRegistry $manager,NotifierInterface $notifier): Response
    {
        $oeuvre = new Oeuvre();
        $user = $this->getUser();
       $oeuvre->setArtisteId($user);
        $form = $this->createForm(OeuvreType::class, $oeuvre);
        $form->handleRequest($request);
   
        if ($form->isSubmitted() && $form->isValid()) {
            // Gérer le téléchargement du fichier
            $file = $form['img']->getData();
            if ($file instanceof UploadedFile) {
                $fileName = md5(uniqid()) . '.' . $file->guessExtension();
                $file->move(
                    $this->getParameter('upload_directory'),
                    $fileName
                );
    
                $originalFileName = $file->getClientOriginalName();
             
                $oeuvre->setImg($fileName);
            }

            try {
                $entityManager = $manager->getManager();
                
                
                
                $entityManager->persist($oeuvre); // Ensure this line is after persisting the notification
                $entityManager->flush();
            
                
            
                return $this->redirectToRoute('app_oeuvre');
            } catch (\Exception $e) {
                $this->addFlash('error', 'Une erreur est survenue lors de l\'enregistrement.');
            }
        }
    
        // Le formulaire n'est pas valide, afficher les erreurs dans le template
        return $this->render('oeuvre/addoeuvre.html.twig', [
            'f' => $form->createView(),
        ]);
    }
    

    #[Route('/artiste/update/{Id}', name: 'app_oeuvre_update')]
    public function updateOeuvre(ManagerRegistry $manager, $Id, OeuvreRepository $rep, Request $req)
    {
        $oeuvre = $rep->find($Id);
        $form = $this->createForm(OeuvreType::class, $oeuvre);
        $form->handleRequest($req);
        if ($form->isSubmitted()&& $form->isValid()) {
            $file = $form['img']->getData();
            if ($file instanceof UploadedFile) {
                $fileName = md5(uniqid()) . '.' . $file->guessExtension();
                $file->move(
                    $this->getParameter('upload_directory'),
                    $fileName
                );

                // Save the original file name in your entity
                $oeuvre->setImg($fileName);
            }

            $manager->getManager()->flush();
            return $this->redirectToRoute('app_oeuvre');
        }
        return $this->render('oeuvre/UpdateOeuvre.html.twig', ['f' => $form->createView()]); //create vue bch ybadel form l html ou renderForm
    }

    
    #[Route('/artiste/oeuvre/delete/{id}', name: 'app_oeuvre_delete')]
    public function deleteOeuvre($id, ManagerRegistry $manager, OeuvreRepository $repo)
    {
        $oeuvre = $repo->find($id);
        $manager->getManager()->remove($oeuvre);
        $manager->getManager()->flush();
        return $this->redirectToRoute('app_oeuvre');
    }

    #[Route('/search/oeuvre', name: 'app_search_oeuvre')]
    public function searchOeuvre(Request $request, OeuvreRepository $repo): JsonResponse
    {
        $searchText = $request->query->get('q');
        $oeuvres = $repo->findBySearchText($searchText); // Implement a custom method in your repository to fetch oeuvres based on search query
    
        // Serialize the oeuvres to JSON and return as response
        $serializedOeuvres = $this->serializeOeuvres($oeuvres); // Implement serialization logic
        return new JsonResponse($serializedOeuvres);
    }
    
    // Implement serialization logic to convert oeuvres to JSON format
    private function serializeOeuvres($oeuvres): array
    {
        // Implement your serialization logic here
        // Example: Convert oeuvres array to associative array or JSON string
        return $oeuvres; // Return serialized oeuvres
    }



    #[Route('/artiste/oeuvre/qrcode/{id}', name: 'oeuvre_qrcode')]
public function generateOeuvreQrCode(int $id): Response
{
    $oeuvre = $this->getDoctrine()->getRepository(Oeuvre::class)->find($id);
    
    if (!$oeuvre) {
        throw $this->createNotFoundException('Oeuvre introuvable');
    }
    
    $qrCodeContent = sprintf(
        "Nom de l'oeuvre : %s\nType de l'oeuvre : %s\nDescription : %s\nDate de publication : %s\nNote : %d\nArtiste : %s\nImage : %s",
        $oeuvre->getNomOeuvre(),
        $oeuvre->getTypeOeuvre(),
        $oeuvre->getDescription(),
        $oeuvre->getDatePublication()->format('Y-m-d'), // Format the date as needed
        $oeuvre->getNote(),
        $oeuvre->getArtisteId()->getNom(),
        $this->getParameter('kernel.project_dir') . '/public/uploads/' . $oeuvre->getImg(),
        // Adjust the path to match the location of your images
    );
    
    // Create the QR code with the content
    $qrCode = QrCode::create($qrCodeContent)
        ->setEncoding(new Encoding('UTF-8'))
        ->setErrorCorrectionLevel(ErrorCorrectionLevel::Low)
        ->setSize(300) // Taille du QR code
        ->setMargin(10) // Marge autour du QR code
        ->setForegroundColor(new Color(0, 0, 0)) // Couleur du QR code
        ->setBackgroundColor(new Color(255, 255, 255)); // Couleur de fond du QR code

    // Optionally, you can add a logo to the QR code
    // $logo = Logo::create('path_to_your_logo.png')->setResizeToWidth(60);

    // Create a label for the QR code
    $label = Label::create('')
        ->setFont(new NotoSans(12)); // Police de caractères de l'étiquette

    // Generate the QR code image with the logo and label
    $writer = new PngWriter();
    $qrCodeImage = $writer->write(
        $qrCode,
        null,
        $label->setText('Scanner ici!!') // Texte de l'étiquette
    )->getDataUri(); // Obtenir les données de l'image au format URI

    // Pass the QR code image data to the Twig template for display
    return $this->render('oeuvre/qrcode.html.twig', [
        'qrCodeImage' => $qrCodeImage,
    ]);
}
#[Route('/oeuvre/qrcode/{id}', name: 'oeuvre_qrcodee')]
public function generateOeuvreQrCodee(int $id): Response
{
    $oeuvre = $this->getDoctrine()->getRepository(Oeuvre::class)->find($id);
    
    if (!$oeuvre) {
        throw $this->createNotFoundException('Oeuvre introuvable');
    }
    
    $qrCodeContent = sprintf(
        "Nom de l'oeuvre : %s\nType de l'oeuvre : %s\nDescription : %s\nDate de publication : %s\nNote : %d\nArtiste : %s\nImage : %s",
        $oeuvre->getNomOeuvre(),
        $oeuvre->getTypeOeuvre(),
        $oeuvre->getDescription(),
        $oeuvre->getDatePublication()->format('Y-m-d'), // Format the date as needed
        $oeuvre->getNote(),
        $oeuvre->getArtisteId()->getNom(),
        $this->getParameter('kernel.project_dir') . '/public/uploads/' . $oeuvre->getImg(),
        // Adjust the path to match the location of your images
    );
    
    // Create the QR code with the content

templates/Oeuvre/oeuvre.html.twig
{% extends 'artiste-dash.html.twig' %}

{% block title %}Liste oeuvres{% endblock %}

{% block body %}
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Your Symfony Project</title>

<style>
.modal-header {
    background-color: #007bff;
    color: #fff;
    border-bottom: 1px solid #dee2e6;
    padding: 15px;
}

/* Modal Body */
.modal-body {
    font-size: 16px;
    line-height: 1.6;
    padding: 20px;
}

/* Modal Footer */
.modal-footer {
    border-top: 1px solid #dee2e6;
    padding: 15px;
}
    .pagination {
    display: flex;
    justify-content: center;
    align-items: center;
}

.pagination a {
    color: black;
    padding: 8px 12px;
    text-decoration: none;
    transition: background-color 0.3s;
    margin: 0 4px;
    border-radius: 4px;
    border: 1px solid #ddd;
}

.pagination a.active,
.pagination a:hover {
    background-color: #f1f1f1;
}

.pagination span.current {
    background-color: #5f76e8;
    color: white;
    padding: 8px 12px;
    border-radius: 4px;
    margin: 0 4px;
}

.pagination a.disabled {
    color: #ddd;
    pointer-events: none;
}

    .card {
        background-color: #fff;
        border-radius: 10px;
        box-shadow: 0 4px 6px rgba(0, 0, 0, 0.1);
        transition: transform 0.3s ease;
    }

    .card:hover {
        transform: translateY(-5px);
    }

    .card img {
        width: 100%;
        height: 200px;
        object-fit: cover;
        border-top-left-radius: 10px;
        border-top-right-radius: 10px;
    }

    .card .card-body {
        padding: 20px;
    }

    .card h5 {
        font-size: 18px;
        font-weight: bold;
        margin-bottom: 10px;
    }

    .card p {
        font-size: 14px;
        color: #666;
    }
</style>
<div class="row justify-content-center mb-4">
    <div class="col-md-6 d-flex align-items-center">
        <button id="sortButton" class="btn btn-primary">Trier par nom</button>
        <div class="customize-input float-right ml-3">
            <a href="{{ path('app_add_oeuvre') }}" class="btn btn-primary">Ajouter Oeuvre</a>
        </div>
    </div>
</div>
<div class="col-md-4">
    <select id="typeOeuvreSelect" class="form-control">
        <option value="all">Tous les types d'oeuvres</option>		
        <option value="FILM">Film</option>
        <option value="CHANSON">Chanson</option>
        <option value="PIECETHEATRE">Pièce de théâtre</option>
    </select>
</div>






<div class="page-breadcrumb">
    <div class="row">
        <div class="col-7 align-self-center">
            <h4 class="page-title text-trunforme text-dark font-weight-medium mb-1">Liste des oeuvres</h4>
            <div class="d-flex align-items-center">
                <nav aria-label="breadcrumb">
                    <ol class="breadcrumb m-0 p-0">
                        <li class="breadcrumb-item">
                            <a href="index.html" class="text-muted">Artiste</a>
                        </li>
                        <li class="breadcrumb-item text-muted active" aria-current="page">Liste oeuvres</li>
                    </ol>
                </nav>
            </div>
        </div>
    </div>
</div>

<div class="row g-4 justify-content-center">
    {% for oeuvre in oeuvres %}
    <div class="col-lg-4 col-md-6 wow fadeInUp" data-wow-delay="0.5s">
        <div class="card" data-type="{{ oeuvre.typeoeuvre|lower }}" data-toggle="modal" data-target="#popup{{ oeuvre.id }}">
            <!-- Replace the ... placeholder with the contents of each card -->
            {% if oeuvre.img %}
                <img src="{{ asset('uploads/' ~ oeuvre.img) }}" alt="Image" class="card-img-top">
            {% else %}
                <span class="card-img-top">Aucune image disponible</span>
            {% endif %}
            <div class="card-body">
                <h5 class="card-title mb-3">Nom de l'oeuvre: {{ oeuvre.nomOeuvre }}</h5>
                <p class="card-text mb-3">Nom de l'artiste: {{ oeuvre.artisteId.nom }}</p>
                <p class="card-text mb-3">Type de l'oeuvre: {{ oeuvre.typeoeuvre }}</p>
				
			</div>
            
        </div>
    </div>


	
    <!-- Modal for each card -->
    <div class="modal fade" id="popup{{ oeuvre.id }}" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Détails de l'oeuvre</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
        <div class="modal-body">
    <!-- Add the content of the popup -->
    		{% if oeuvre.img %}
        		<img src="{{ asset('uploads/' ~ oeuvre.img) }}" alt="Image" class="card-img-top mb-3">
    		{% else %}
        		<span class="card-img-top">Aucune image disponible</span>
    		{% endif %}
    		<p><strong>Nom de l'oeuvre:</strong> {{ oeuvre.nomOeuvre }}</p>
    		<p><strong>Nom de l'artiste:</strong> {{ oeuvre.artisteId.nom }}</p>
    		<p><strong>Type de l'oeuvre:</strong> {{ oeuvre.typeoeuvre }}</p>
    		<p><strong>Description:</strong> {{ oeuvre.description }}</p>
    <!-- Add like and dislike buttons -->
    		<link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css" rel="stylesheet">

<!-- Replace the like and dislike buttons with icons -->
<div class="modal-body">
    <!-- Add the content of the popup -->
    <!-- Other content remains unchanged -->

    <!-- Add icons for like and dislike buttons -->
    <button class="btn btn-primary like-btn" id="like-btn" data-id="{{ oeuvre.id }}">
        <i class="fas fa-thumbs-up"></i> <!-- Like icon -->
    </button>
    <button class="btn btn-danger dislike-btn" id="dislike-btn" data-id="{{ oeuvre.id }}">
        <i class="fas fa-thumbs-down"></i> <!-- Dislike icon -->
    </button>
</div>


		</div>
		<div id="like-dislike-message"></div>

            <div class="modal-footer">
                <!-- Add the button to view the QR code -->
                <a href="{{ path('oeuvre_qrcode', {'id': oeuvre.id}) }}" class="btn btn-primary">Voir le QR Code</a>
                <a href="{{ path('app_oeuvre_update', {'Id': oeuvre.id}) }}" class="btn btn-warning">Modifier</a>
                <a href="{{ path('app_oeuvre_delete', {'id': oeuvre.id}) }}" class="btn btn-danger">Supprimer</a>
            </div>
			
        </div>
		<div class="modal fade" id="likeDislikeModal" tabindex="-1" aria-labelledby="likeDislikeModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="likeDislikeModalLabel">Message</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <p id="likeDislikeMessage"></p>
            </div>
    </div>
</div>
        </div>
    </div>
</div>

    {% endfor %}
</div>

<!-- Pagination Links -->
<div class="container">
    <div class="d-flex justify-content-center">
        <div class="pagination">
            {{ knp_pagination_render(oeuvres) }}
        </div>
    </div>
</div>


<!-- Delete Modals -->
{% for form in oeuvres %}
		<div class="modal fade" id="deleteModal{{ form.id }}"aria-labelledby="deleteModalLabel{{ form.id }}" aria-hidden="true">
			<div class="modal-dialog">
				<div class="modal-content">
					<div class="modal-header">
						<h5 class="modal-title" id="deleteModalLabel{{ form.id }}">Confirmer Supprission</h5>
						<button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
					</div>
					<div class="modal-body">
						Etes-vous sûr que vous voulez supprimer "{{ form.nomOeuvre }}"?
					</div>
					<div class="modal-footer">
						<button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Fermer</button>
						<a href="{{ path('app_oeuvre_delete', {'id': form.id}) }}" class="btn btn-danger">Supprimer</a>

					</div>
				</div>
			</div>
		</div>
	{% endfor %}
<!-- jQuery -->
<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>

<!-- Bootstrap JS -->
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.bundle.min.js"></script>

<script>
$(document).ready(function() {
    $('#searchInput').on('keyup', function() {
        var searchText = $(this).val().toLowerCase().trim();
        filterCards(searchText);
    });

    $('#sortButton').on('click', function() {
        toggleSortOrder();
    });
	$('#typeOeuvreSelect').on('change', function() {
    var type = $(this).val();
    if (type === 'all') {
            // Reload the page to show all oeuvres
            window.location.href = "{{ path('app_artiste_oeuvre') }}";
        } else {
            filterOeuvreByType(type);
        }
    window.location.href = '{{ path('app_artiste_oeuvre') }}?typeoeuvre=' + type;
});
});
function filterOeuvreByType(type) {
    $.ajax({
        url: '{{ path('app_filter_oeuvre_by_type') }}',
        method: 'GET',
        data: { type: type },
        success: function(response) {
            // Replace the HTML content of the container with the filtered oeuvres
            $('#cardsContainer').html(response);
        },
        error: function(xhr, status, error) {
            console.error(error);
        }
    });
}

var ascendingOrder = true;
var originalCardsOrder = null;

function toggleSortOrder() {
    ascendingOrder = !ascendingOrder; // Toggle the sorting order

    if (ascendingOrder) {
        sortCardsAlphabetically();
    } else {
        restoreOriginalOrder();
    }
}

function sortCardsAlphabetically() {
    var cardsContainer = $('.row.g-4.justify-content-center');
    var cards = cardsContainer.find('.card').toArray();

    cards.sort(function(a, b) {
        var nameA = $(a).find('.card-title').text().toLowerCase();
        var nameB = $(b).find('.card-title').text().toLowerCase();
        return nameA.localeCompare(nameB);
    });

    cardsContainer.empty();
    cards.forEach(function(card) {
        cardsContainer.append(card);
    });
}

function restoreOriginalOrder() {
    if (originalCardsOrder !== null) {
        $('.row.g-4.justify-content-center').empty().append(originalCardsOrder);
    }
}

// Call this function when the page is loaded to store the original order of cards
function storeOriginalOrder() {
    originalCardsOrder = $('.row.g-4.justify-content-center').html();
}

// Store the original order when the page is loaded
$(window).on('load', function() {
    storeOriginalOrder();
});

function filterCards(searchText) {
    var cardsToShow = $('.card').filter(function() {
        var cardText = $(this).text().toLowerCase();
        return cardText.includes(searchText);
    });

    if (cardsToShow.length > 0) {
        $('.no-cards-message').hide(); // Hide the message if there are cards to show
        $('.card').hide(); // Hide all cards initially
        cardsToShow.show(); // Show only the filtered cards
    } else {
        $('.card').hide(); // Hide all cards if no cards match the search criteria
        $('.no-cards-message').show(); // Show the message
    }
}
</script>

<script>
document.addEventListener('DOMContentLoaded', function() {
    const searchInput = document.getElementById('searchInput');
    const cardsContainer = document.getElementById('cardsContainer');

    searchInput.addEventListener('input', function(event) {
        const searchTerm = event.target.value.trim().toLowerCase();
        const cards = Array.from(cardsContainer.getElementsByClassName('card'));

        cards.forEach(function(card) {
            const cardText = card.textContent.trim().toLowerCase();

            if (cardText.includes(searchTerm)) {
                card.style.display = 'block';
            } else {
                card.style.display = 'none';
            }
        });
    });
});
</script>
<script>
$(document).ready(function() {
    // Other existing code...

    // Event listener for like button click
    $(document).on('click', '.like-btn', function() {
        var oeuvreId = $(this).data('id');
        // Here you can perform an AJAX request to handle liking the artwork
        // For now, let's just display a message in a modal popup
        $('#likeDislikeMessage').text('You liked the artwork.');
        $('#likeDislikeModal').modal('show');
    });

    // Event listener for dislike button click
    $(document).on('click', '.dislike-btn', function() {
        var oeuvreId = $(this).data('id');
        // Similar to the like button, handle disliking the artwork here
        // For now, let's just display a message in a modal popup
        $('#likeDislikeMessage').text('You disliked the artwork.');
        $('#likeDislikeModal').modal('show');
    });
});
</script>




{% endblock %}